### ISSUE TITLE
404 Error upon Twitter auth validation (2)

### ISSUE THREAD

**Issue by j2is** [ssplugin/ss-twitter-feed#6]
I unfortunately can't get the plugin to authorise, it redirects to a 404 after authentication

**Comment by ssplugin** [comment]
Please describe more about this issue. 
It looks like your site URL different to the main URL. Because when the authentication process complete you are redirected to your current craft site. So please match your site URL and Base URL are same?.

Thanks.

**Comment by devotoare** [comment]
Still very much an issue. I've spent about an hour trying to get the plugin to authorize using every variation of this suggestion humanly possible. It does not work.

This is the error log I get:

```
Next yii\web\NotFoundHttpException: Page not found. in /var/www/html/vendor/craftcms/cms/src/web/Application.php:570
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/Application.php(278): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#1 /var/www/html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#2 /var/www/html/web/index.php(21): yii\base\Application->run()
#3 {main}
$_SERVER = [
    'COMPOSER_NO_INTERACTION' => '1',
    'DB_SERVER' => 'mysql',
    'PHP_MD5' => '',
    'SECURITY_KEY' => '[REDACTED]',
    'PHP_URL' => 'https://www.php.net/get/php-7.2.20.tar.xz/from/this/mirror',
    'DB_PORT' => '3306',
    'ENVIRONMENT' => 'staging',
    'SUPERVISOR_GROUP_NAME' => 'php-fpm',
    'S3_SECRET' => '',
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    'DB_DATABASE' => '[REDACTED]',
    'SHLVL' => '2',
    'SUPERVISOR_ENABLED' => '1',
    'DB_USER' => '[REDACTED]',
    'PHP_VERSION' => '7.2.20',
    'HOME' => '/home/www',
    'LD_PRELOAD' => '/usr/lib/preloadable_libiconv.so php',
    'SUPERVISEDIR' => '/tmp/supervised/',
    'DB_PASSWORD' => '[REDACTED]',
    'S3_BUCKET' => '',
    'DB_DRIVER' => 'mysql',
    'S3_API_KEY' => '',
    'DEFAULT_SITE_URL' => 'basic.example.site.com',
    'DB_SCHEMA' => 'public',
    'PHP_INI_DIR' => '/usr/local/etc/php',
    '_' => '/usr/bin/supervisord',
    'PHP_CPPFLAGS' => '-fstack-protector-strong -fpic -fpie -O2',
    'PHP_CFLAGS' => '-fstack-protector-strong -fpic -fpie -O2',
    'PHP_EXTRA_CONFIGURE_ARGS' => '--enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi',
    'SUPERVISOR_PROCESS_NAME' => 'php-fpm_00',
    'PHPIZE_DEPS' => 'autoconf 		dpkg-dev dpkg 		file 		g++ 		gcc 		libc-dev 		make 		pkgconf 		re2c',
    'HOSTNAME' => '2e998277bb85',
    'S3_REGION' => '',
    'PWD' => '/var/www/html',
    'PHP_LDFLAGS' => '-Wl,-O1 -Wl,--hash-style=both -pie',
    'PHP_ASC_URL' => 'https://www.php.net/get/php-7.2.20.tar.xz.asc/from/this/mirror',
    'TEMP' => '/tmp',
    'TMPDIR' => '/tmp',
    'TMP' => '/tmp',
    'USER' => 'www',
    'HTTP_X_REAL_IP' => '[REDACTED]',
    'HTTP_X_FORWARDED_SERVER' => '[REDACTED]',
    'HTTP_X_FORWARDED_PROTO' => 'https',
    'HTTP_X_FORWARDED_PORT' => '443',
    'HTTP_X_FORWARDED_HOST' => 'basic.example.site.com',
    'HTTP_X_FORWARDED_FOR' => '[REDACTED]',
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1',
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36',
    'HTTP_HOST' => 'basic.example.site.com',
    'PATH_INFO' => '',
    'SCRIPT_FILENAME' => '/var/www/html/web/index.php',
    'REDIRECT_STATUS' => '200',
    'SERVER_NAME' => '_',
    'SERVER_PORT' => '8080',
    'SERVER_ADDR' => '10.0.1.70',
    'REMOTE_PORT' => '48000',
    'REMOTE_ADDR' => '10.0.1.136',
    'SERVER_SOFTWARE' => 'nginx/1.16.0',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'REQUEST_SCHEME' => 'http',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'DOCUMENT_ROOT' => '/var/www/html/web',
    'DOCUMENT_URI' => '/index.php',
    'REQUEST_URI' => '/actions/ss-twitter-feed/oauth/callback&oauth_token=[REDACTED]&oauth_verifier=[REDACTED]',
    'SCRIPT_NAME' => '/index.php',
    'CONTENT_LENGTH' => '',
    'CONTENT_TYPE' => '',
    'REQUEST_METHOD' => 'GET',
    'QUERY_STRING' => 'q=/actions/ss-twitter-feed/oauth/callback&oauth_token=[REDACTED]&oauth_verifier=[REDACTED]&',
    'FCGI_ROLE' => 'RESPONDER',
    'PHP_SELF' => '/index.php',
    'REQUEST_TIME_FLOAT' => 1564088157.811762,
    'REQUEST_TIME' => 1564088157,
    'argv' => [
        'q=/actions/ss-twitter-feed/oauth/callback&oauth_token=[REDACTED]&oauth_verifier=[REDACTED]&',
    ],
    'argc' => 1,
]
```

**Comment by terryupton** [comment]
@devotoaredid you manage to resolve this? I am getting a 404 error too after the redirection back from Twitter. I am working locally using Valet .

**Comment by devotoare** [comment]
@terryupton We did get it working but I'm really not sure how. It's been too long. I know we made a couple code changes and made a pull request that's been merged in but I don't think it was related to this. I think we ended up having to push to a production-like environment to get it to work and then pull in the database changes from the remote server.... 

Don't quote me on that, it's a 6 month old fuzzy memory.

**Comment by ssplugin** [comment]
@j2is @devotoare @terryupton 

We need more explanation from you because we have tested our environment and working fine.
Please match your site URL with redirecting back URL to the site from Twitter.
For example: ( Compare URL part before `/action/..` )
**Site URL** = https://xyz.com/
**Redirect URL** = https://xyz.com/actions/ss-twitter-feed/oauth/callback&oauth_token=RdfsffsAABaYIFtds&oauth_verifier=fsdfMOVEvsO3YsdfsfsY22kFlKcBIOA2yU

Have you change the cpTrigger URL into the `config/general.php` file. If yes then explain...

Thanks
